spring:
  profiles:
    active: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/springdb
    username: sa
    password:
mybatis:
  type-aliases-package: hello.itemservice.domain
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    hello.itemservice.repository.mybatis: TRACE
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
